### ISSUE TITLE
Support for domain/hostnames

### ISSUE THREAD

**Issue by mgpai22** [Satergo/ErgoSock#1]
Is it possible to add support for domain/hostnames?

For example I want to use `https://node.sigmaspace.io` rather than an ip address.

I tried something like this 
```java
    public ErgoSocket(String hostname, int port, Peer self, byte[] networkMagic) throws IOException {
        super(hostname, port);
        this.self = self;
        this.networkMagic = networkMagic;
        this.in = new DataInputStream(this.getInputStream());
    }
```
This does not work for everything. 

- `https://node.sigmaspace.io` - this does not work
- `https://ergo-node.zoomout.io` - this works

I think the first one does not work due to some reverse proxy requiring access from `sigmaspace` domain rather than an ip.

**Comment by satsen** [comment]
This is TCP/IP, so, HTTP or HTTPS is not relevant here. There is no concept of domains in TCP, as the domain is resolved to an IP address before connecting to the target. This means that domains are already supported.

The constructor takes an InetSocketAddress, and you can provide a domain to InetSocketAddress and it will just work. It seems to me that `node.sigmaspace.io` doesn't actually have their node public, only the HTTP API is public (which is a strange choice). So, you should ask them to make it public if you want to connect to their node.

**Comment by mgpai22** [comment]
Problem comes from reverse proxies more so than anything. 

They only allow programs to be accessed if you use domain. If you use ip address, it will not load. Cloudflare proxy also plays a role in this. This feature allows the actual ip of a program to be hidden.

**Comment by satsen** [comment]
Either way it's on their side and not a problem with the library.
