### ISSUE TITLE
Add block number subscription

### ISSUE THREAD

**Issue by mgpai22** [Satergo/ErgoSock#2]
Please add some way of getting notified by the block number just like how the header ids work.

**Comment by satsen** [comment]
The Header modifier contains both an `id` as well as a `height`, is this what you are looking for? Maybe you missed that the second field is also present.

**Comment by mgpai22** [comment]
Could you please provide an example?

**Comment by satsen** [comment]
Well,

```java
if (modifier.typeId() == Header.TYPE_ID) {
	Header header = Header.deserialize(modifier.id(), modifier.object());
	System.out.println(header.height() + " " + HexFormat.of().formatHex(header.id()));
}
```
