### ISSUE TITLE
Testnet Magic Error

### ISSUE THREAD

**Issue by mgpai22** [Satergo/ErgoSock#3]
Testnet Magic is `public static final byte[] TESTNET_MAGIC = new byte[]{2, 0, 2, 3};`
The network port is `9022`

With these values I get magic errors
```
Error occured: incorrect magic [2, 0, 2, 3] (must be [1, 0, 2, 4])
Error occured: incorrect magic [65, 0, 0, 0] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-31, -68, 91, 0] (must be [1, 0, 2, 4])
Error occured: incorrect magic [101, 0, -1, 1] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-36, 1, 3, 110] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-28, -32, 115, 76] (must be [1, 0, 2, 4])
Error occured: incorrect magic [54, -67, 48, 26] (must be [1, 0, 2, 4])
Error occured: incorrect magic [95, 108, 56, -58] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-41, -25, -1, 7] (must be [1, 0, 2, 4])
Error occured: incorrect magic [91, -45, 102, 115] (must be [1, 0, 2, 4])
Error occured: incorrect magic [57, -48, 98, 121] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-103, 21, 102, 3] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-57, 46, 9, 8] (must be [1, 0, 2, 4])
Error occured: incorrect magic [121, 119, 90, -85] (must be [1, 0, 2, 4])
Error occured: incorrect magic [-84, -44, 79, -16] (must be [1, 0, 2, 4])
Error occured: incorrect magic [54, -116, 83, 51] (must be [1, 0, 2, 4])
Error occured: incorrect magic [1, -27, 51, 60] (must be [1, 0, 2, 4])
```

**Comment by satsen** [comment]
When connecting to testnet nodes, you need to use the `ErgoSocket(InetSocketAddress address, Peer self, byte[] networkMagic)` constructor, like this: `new ErgoSocket(address, self, ErgoSocket.TESTNET_MAGIC)`.

However, it seems like you have a custom network that uses [2, 0, 2, 3] as the magic number (I'm not sure), in that case, use `new ErgoSocket(address, self, new byte[] { 2, 0, 2, 3 })`.

**Comment by satsen** [comment]
If you're curious, the reason the subsequent messages have seemingly completely random magic numbers is that since TCP is stream-based, and matching an invalid magic number causes the message-reading to abort, the next calls to acceptMessage() are reading that unread data from the first message.

Perhaps I should make it close the socket when it matches an invalid magic number, as it is not really convenient for users to recover from that state of unread messages (they would have to read the stream manually), and really, an incorrect magic number very likely means something was misconfigured.

**Comment by mgpai22** [comment]
> When connecting to testnet nodes, you need to use the `ErgoSocket(InetSocketAddress address, Peer self, byte[] networkMagic)` constructor, like this: `new ErgoSocket(address, self, ErgoSocket.TESTNET_MAGIC)`.
> 
> However, it seems like you have a custom network that uses [2, 0, 2, 3] as the magic number (I'm not sure), in that case, use `new ErgoSocket(address, self, new byte[] { 2, 0, 2, 3 })`.

Yes I have done that. `2023` is the magic of the current testnet

**Comment by satsen** [comment]
@mgpai22 Are you sure you manually provided `new byte[] { 2, 0, 2, 3 }` to that constructor? The error message makes it seem like the MAINNET magic was provided

**Comment by satsen** [comment]
And I had no idea the testnet's magic number was changed, so I'll change that utility static field, thanks for letting me know.

**Comment by mgpai22** [comment]
> @mgpai22 Are you sure you manually provided `new byte[] { 2, 0, 2, 3 }` to that constructor? The error message makes it seem like the MAINNET magic was provided

Yes I am positive. It works for like the first five minutes the breaks

**Comment by mgpai22** [comment]
> And I had no idea the testnet's magic number was changed, so I'll change that utility static field, thanks for letting me know.

Yes I changed it a year ago

**Comment by satsen** [comment]
> Yes I am positive. It works for like the first five minutes the breaks

Any chance you could show me some code, as far as I can see there is nothing that could cause the MAINNET magic to be printed in the exception thrown if you passed it something else. All I can think of is that:
- either you modified this byte array (arrays are mutable)
- or you instantiated another socket in the same program but this time with the MAINNET magic, this could be the case if you have re-connection logic, maybe you accidentally provide the wrong magic in the reconnection socket, which would explain why it breaks after some time

**Comment by mgpai22** [comment]
I use this https://github.com/mgpai22/ergo-node-zmqpub

1) Change docker-compose.yml to this
```
version: '3'

services:
  ergo-node-zmqpub:
    container_name: ergo-node-zmqpub
    build: .
    ports:
      - "9060:9060"
    restart: unless-stopped
    volumes:
      - ./config.json:/path/to/config.json
  ergo-node-zmqpub-testnet:
    container_name: ergo-node-zmqpub-testnet
    build: .
    ports:
      - "9070:9070"
    restart: unless-stopped
    volumes:
      - ./config-testnet.json:/app/config.json
```

2) config-testnet.json 
```
{
  "nodeURL": "http://168.138.185.215:9052",
  "nodePeersPort": "9022",
  "zmqIP": "0.0.0.0",
  "zmqPort": "9070"
}
```

3) config.json
```
{
  "nodeURL": "http://213.239.193.208:9053",
  "nodePeersPort": "9030",
  "zmqIP": "0.0.0.0",
  "zmqPort": "9060"
}
```

4) Run `docker compose up -d`

**Comment by satsen** [comment]
Well, my 2nd guess was correct. You have reconnection logic and in there you don't supply the correct magic number.

See: https://github.com/mgpai22/ergo-node-zmqpub/blob/main/src/main/scala/io/cruxfinance/EventPublish.scala#L131-L140
